version: '3.2'
services:

  flask_app:
    build:
      dockerfile: Dockerfile
      context: ./flaskIOT
    ports:
      - 5000:5000
    image: mick2k1/iotflask
    container_name: iotproj
    environment:
      - TG_TOKEN=5887797061:AAEvYrnkdgFwS5nKmfoSJXNck-kzefUFEC0
  bot_telegram:
    build:
        dockerfile: Dockerfile
        context: ./telegram_bot

    image: 267759/botflask:1.0    
    container_name: botflask
    environment:
        - TG_TOKEN=5887797061:AAEvYrnkdgFwS5nKmfoSJXNck-kzefUFEC0
        - URL=http://iotproj:5000/db/

  nextjs_app:
    image: mick2k1/iot-nextjs-fe
    container_name: nextjs_app
    ports:
      - "3000:3000"

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.2
    restart: always
    profiles:
        - donotstart
    ports:
        - "8080:8080"
    environment:
        PBF_URL: https://gmichele.it/modena.osm.pbf
        NOMINATIM_PASSWORD: password
    volumes:
#       - ~/nominatim/osm_extract/:/nominatim/data/
        - ~/nominatim/nominatim-data:/var/lib/postgresql/14/main
    shm_size: 256mb

volumes:
    nominatim-data:
