version: '3.2'
services:
  flask_app:
    build:
      dockerfile: Dockerfile
      context: ./flaskIOT
    ports:
      - 5000:5000
    image: mick2k1/iotflask
    container_name: iotproj
    environment:
      - TEMP=null
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.2
    restart: always
    profiles:
        - donotstart
    ports:
        - "8080:8080"
    environment:
        PBF_URL: https://gmichele.it/modena.osm.pbf
        NOMINATIM_PASSWORD: password
    volumes:
#          - ~/nominatim/osm_extract/:/nominatim/data/
        - ~/nominatim/nominatim-data:/var/lib/postgresql/14/main
    shm_size: 256mb

volumes:
    nominatim-data:
