version: '3.2'
services:
  flask_app:
    build:
      dockerfile: Dockerfile
      context: ./flaskIOT
    ports:
      - 5000:5000
    image: iotflask
    container_name: iotproj
    environment:
      - TEMP=null