version: '3.2'
services:

  flask_app:
    build:
      dockerfile: Dockerfile
      context: ./flaskIOT
    ports:
      - 5000:5000
    image: mick2k1/iotflask
    container_name: iotproj
    environment:
      - TG_TOKEN=5887797061:AAEvYrnkdgFwS5nKmfoSJXNck-kzefUFEC0
      - OPENROUTESERVICE_KEY=5b3ce3597851110001cf62481c69b9fec9a84097a32947ecbc631599
      - WEATHER_KEY=8db7edbf3f049e2543fb1115755351c0
      - FLASK_CONFIG=docker_local
      - FAKER=True
      - URL_REVERSE=https://osm.gmichele.it/reverse
  bot_telegram:
    build:
        dockerfile: Dockerfile
        context: ./telegram_bot

    image: 267759/botflask:1.0    
    container_name: botflask
    environment:
        - TG_TOKEN=5887797061:AAEvYrnkdgFwS5nKmfoSJXNck-kzefUFEC0
        - URL_db=http://iotproj:5000/db/
        - URL_get=http://iotproj:5000/get/
        - URL_set=http://iotproj:5000/set/
        - URL_check=http://iotproj:5000/check/
    profiles:
      - donotstart

  nextjs_app:
    image: mick2k1/iot-nextjs-fe
    profiles:
      - donotstart
    container_name: nextjs_app
    ports:
      - "3000:3000"

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.2
    restart: always
    profiles:
        - donotstart
    ports:
        - "8080:8080"
    environment:
        PBF_URL: https://gmichele.it/modena.osm.pbf
        NOMINATIM_PASSWORD: password
    volumes:
#       - ~/nominatim/osm_extract/:/nominatim/data/
        - ~/nominatim/nominatim-data:/var/lib/postgresql/14/main
    shm_size: 256mb

volumes:
    nominatim-data:
