version: '3'

services:
  next-app:
    container_name: iot-react-fe
    image: mick2k1/iot-react-fe
    build:
      context: ./app
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 3000:3000
  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname